name: Linter 

on :
    push : null 
    pull_request: null 

jobs : 
    checkout: 
        name : Lint
        runs-on : unbutu-latest

        steps : 
            - name : Checkout code 
              uses:  actions/checkout@v4

              env : 
                DEFAULT_BRANCH : main 
                GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}